// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSuw9CVzoQNUJ0ySkDVZetafdMGdqtTmg',
    appId: '1:545150302344:web:232cc1583af3d62e5fc73d',
    messagingSenderId: '545150302344',
    projectId: 'cricket-plus-live',
    authDomain: 'cricket-plus-live.firebaseapp.com',
    storageBucket: 'cricket-plus-live.firebasestorage.app',
    measurementId: 'G-J867G5LCGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC__sWz-dFG2a8glJMJYanl1MQgcKbqu_M',
    appId: '1:545150302344:android:12533aeb6abe2d635fc73d',
    messagingSenderId: '545150302344',
    projectId: 'cricket-plus-live',
    storageBucket: 'cricket-plus-live.firebasestorage.app',
  );
}
